[workspace]
members = ["gui", "shellext"]
resolver = "2"

[workspace.package]
version = "0.2.1"
edition = "2021"

[profile.release]
strip = true
lto = true

[package]
name = "aahl"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
blake3 = "1"
anyhow = "1"
rayon = "1"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
