//! COM class implementations for the AAHL shell extension.
//!
//! Two classes are exported through [`crate::DllGetClassObject`]:
//!
//! * `AahlMenuExt` — implements `IShellExtInit` + `IContextMenu`. The shell
//!   drops a file list into it via `Initialize`, then the context menu
//!   commands (Add / Extract here / Extract to / Test) run the AAHL CLI in
//!   the background and report the result with a message box.
//! * `AahlClassFactory` — `IClassFactory` that hands out `AahlMenuExt`
//!   instances and refuses aggregation.

use std::ffi::c_void;
use std::sync::Mutex;

use windows::core::{implement, BOOL, ComObject, GUID, Interface, Ref, Result, HRESULT, PCWSTR, PSTR};
use windows::Win32::Foundation::{
    CLASS_E_NOAGGREGATION, E_INVALIDARG, E_NOINTERFACE, E_POINTER, HGLOBAL,
};
use windows::Win32::System::Com::{IClassFactory, IClassFactory_Impl, IDataObject};
use windows::Win32::UI::Shell::{
    Common, CMINVOKECOMMANDINFO, CMINVOKECOMMANDINFOEX, GCS_VERBA, GCS_VERBW,
    GCS_VALIDATEW, IContextMenu, IContextMenu_Impl, IShellExtInit, IShellExtInit_Impl,
};
use windows::Win32::UI::WindowsAndMessaging::{
    InsertMenuW, MF_BYPOSITION, MF_STRING, MENU_ITEM_FLAGS, HMENU,
};
use windows::core::IUnknown;

/// CMIC_MASK_UNICODE (0x1): `lpVerbW` is authoritative when the invoke info
/// block is a `CMINVOKECOMMANDINFOEX`. Not generated by `windows` 0.62, so it
/// is defined here.
const CMIC_MASK_UNICODE: u32 = 0x0000_0001;

use crate::menu::{self, Verb};
use crate::tool;

/// Context menu extension. `selection` holds the file list captured by
/// `IShellExtInit::Initialize`; `id_cmd_first` is the first command id the
/// menu handed out so `InvokeCommand`/`GetCommandString` can map ids back to
/// verbs.
#[implement(IShellExtInit, IContextMenu)]
pub struct AahlMenuExt {
    pub selection: Mutex<Option<Vec<String>>>,
    pub id_cmd_first: Mutex<Option<u32>>,
}

impl AahlMenuExt {
    /// Create a fresh extension instance (refcount 1, owned by the caller).
    pub fn new() -> ComObject<Self> {
        ComObject::new(Self {
            selection: Mutex::new(None),
            id_cmd_first: Mutex::new(None),
        })
    }
}

/// Read the HDROP file list stored in a global memory block.
fn read_hdrop(hglobal: HGLOBAL) -> Vec<String> {
    use windows::Win32::UI::Shell::{DragQueryFileW, HDROP};

    if hglobal.0.is_null() {
        return Vec::new();
    }
    let hdrop = HDROP(hglobal.0);
    let mut files = Vec::new();
    unsafe {
        let count = DragQueryFileW(hdrop, u32::MAX, None);
        files.reserve(count as usize);
        for index in 0..count {
            let length = DragQueryFileW(hdrop, index, None);
            let mut buffer = vec![0u16; length as usize + 1];
            let written = DragQueryFileW(hdrop, index, Some(&mut buffer)) as usize;
            let mut end = written.min(buffer.len());
            while end > 0 && buffer[end - 1] == 0 {
                end -= 1;
            }
            if let Ok(text) = String::from_utf16(&buffer[..end]) {
                if !text.is_empty() {
                    files.push(text);
                }
            }
        }
    }
    files
}

/// Implementation helpers attached to the generated `AahlMenuExt_Impl`
/// wrapper (which derefs to `AahlMenuExt`, so the fields are reachable as
/// `self.*`).
impl AahlMenuExt_Impl {
    /// Capture the dropped file list. Failures to read the drop data are not
    /// errors for the shell — the menu simply shows no commands.
    fn extract_files(&self, data: Ref<IDataObject>) -> Result<()> {
        use windows::Win32::System::Com::{DVASPECT_CONTENT, FORMATETC, TYMED_HGLOBAL};
        use windows::Win32::System::Ole::CF_HDROP;
        use windows::Win32::System::Ole::ReleaseStgMedium;

        let Some(data) = data.as_ref() else {
            return Ok(());
        };
        let format = FORMATETC {
            cfFormat: CF_HDROP.0,
            ptd: std::ptr::null_mut(),
            dwAspect: DVASPECT_CONTENT.0,
            lindex: -1,
            tymed: TYMED_HGLOBAL.0 as u32,
        };
        let Ok(mut medium) = (unsafe { data.GetData(&format) }) else {
            return Ok(());
        };
        let files = unsafe { read_hdrop(medium.u.hGlobal) };
        let _ = unsafe { ReleaseStgMedium(&mut medium as *mut _) };
        *self.selection.lock().unwrap() = if files.is_empty() {
            None
        } else {
            Some(files)
        };
        Ok(())
    }

    /// Run the action for `verb` using the executables resolved by
    /// [`tool::discover`]. Progress is invisible (CREATE_NO_WINDOW); the
    /// completion or failure is reported with a message box.
    fn execute(&self, verb: Verb, selection: &[String]) {
        let binaries = tool::discover();
        let archive = tool::archive_path(selection);
        match verb {
            Verb::Add => tool::run_action(
                binaries.gui.clone(),
                tool::add_arguments(selection),
                &std::env::temp_dir(),
                "Adding to AAHL archive",
            ),
            Verb::ExtractHere => {
                let target = tool::extract_target(&archive, None);
                let _ = std::fs::create_dir_all(&target);
                tool::run_action(
                    binaries.cli.clone(),
                    tool::extract_arguments(&archive, &target),
                    &target,
                    "Extracting AAHL archive",
                );
            }
            Verb::ExtractTo => {
                let stem = menu::stem(&archive.to_string_lossy());
                let target = tool::extract_target(&archive, Some(&stem));
                let _ = std::fs::create_dir_all(&target);
                tool::run_action(
                    binaries.cli.clone(),
                    tool::extract_arguments(&archive, &target),
                    &target,
                    "Extracting AAHL archive",
                );
            }
            Verb::Test => tool::run_action(
                binaries.cli.clone(),
                tool::test_arguments(&archive),
                &std::env::temp_dir(),
                "Testing AAHL archive",
            ),
        }
    }
}

impl IShellExtInit_Impl for AahlMenuExt_Impl {
    fn Initialize(
        &self,
        _pidlfolder: *const Common::ITEMIDLIST,
        pdtobj: Ref<IDataObject>,
        _hkeyprogid: windows::Win32::System::Registry::HKEY,
    ) -> Result<()> {
        self.extract_files(pdtobj)
    }
}

impl IContextMenu_Impl for AahlMenuExt_Impl {
    fn QueryContextMenu(
        &self,
        hmenu: HMENU,
        indexmenu: u32,
        idcmdfirst: u32,
        idcmdlast: u32,
        uflags: u32,
    ) -> HRESULT {
        // CMF_DEFAULTONLY: the shell only wants the default command, and this
        // extension does not designate one.
        if uflags & 0x1 != 0 {
            return HRESULT(0);
        }
        let selection = self.selection.lock().unwrap().clone();
        let Some(selection) = selection else {
            return HRESULT(0);
        };
        let (verbs, stem) = menu::build(&selection);
        if verbs.is_empty() {
            return HRESULT(0);
        }

        let mut inserted: u32 = 0;
        for (index, verb) in verbs.iter().enumerate() {
            let id = idcmdfirst.wrapping_add(index as u32);
            if id > idcmdlast {
                break;
            }
            let label = tool::wide(&verb.label(stem.as_deref()));
            let inserted_ok = unsafe {
                InsertMenuW(
                    hmenu,
                    indexmenu.wrapping_add(inserted),
                    MENU_ITEM_FLAGS(MF_BYPOSITION.0 | MF_STRING.0),
                    id as usize,
                    PCWSTR::from_raw(label.as_ptr()),
                )
            };
            if inserted_ok.is_err() {
                break;
            }
            inserted += 1;
        }
        if inserted > 0 {
            *self.id_cmd_first.lock().unwrap() = Some(idcmdfirst);
        }
        HRESULT(inserted as i32)
    }

    fn InvokeCommand(&self, pici: *const CMINVOKECOMMANDINFO) -> Result<()> {
        if pici.is_null() {
            return Err(E_POINTER.into());
        }
        let info = unsafe { &*pici };
        if info.cbSize < std::mem::size_of::<CMINVOKECOMMANDINFO>() as u32 {
            return Err(E_INVALIDARG.into());
        }
        let selection = self.selection.lock().unwrap().clone();
        let Some(selection) = selection else {
            return Ok(());
        };
        if selection.is_empty() {
            return Ok(());
        }

        let first = self.id_cmd_first.lock().unwrap().unwrap_or(0);
        let (verbs, _stem) = menu::build(&selection);

        // Resolve the verb: wide name, ANSI name, then numeric id.
        let mut verb = None;
        if !info.lpVerb.is_null() {
            let is_ex = info.cbSize >= std::mem::size_of::<CMINVOKECOMMANDINFOEX>() as u32;
            let is_unicode = is_ex && (info.fMask & CMIC_MASK_UNICODE) != 0;
            if is_unicode {
                let ex = info as *const CMINVOKECOMMANDINFO as *const CMINVOKECOMMANDINFOEX;
                let wide = unsafe { (*ex).lpVerbW };
                if !wide.is_null() {
                    let mut units = Vec::new();
                    let mut cursor = wide.0;
                    loop {
                        let unit = unsafe { *cursor };
                        if unit == 0 {
                            break;
                        }
                        units.push(unit);
                        cursor = unsafe { cursor.add(1) };
                    }
                    verb = menu::verb_from_name_wide(&units);
                }
            } else {
                let mut bytes = Vec::new();
                let mut cursor = info.lpVerb.0;
                loop {
                    let byte = unsafe { *cursor };
                    if byte == 0 {
                        break;
                    }
                    bytes.push(byte);
                    cursor = unsafe { cursor.add(1) };
                }
                verb = menu::verb_from_name(&bytes);
            }
            // Numeric id form: the id is carried in the LOWORD of lpVerb.
            if verb.is_none() {
                verb = menu::verb_from_id(&verbs, info.lpVerb.0 as usize as u32 & 0xFFFF, first);
            }
        }
        let Some(verb) = verb else {
            return Ok(());
        };
        self.execute(verb, &selection);
        Ok(())
    }

    fn GetCommandString(
        &self,
        idcmd: usize,
        utype: u32,
        _preserved: *const u32,
        pszname: PSTR,
        cchmax: u32,
    ) -> Result<()> {
        if pszname.0.is_null() {
            return Err(E_INVALIDARG.into());
        }
        let selection = self.selection.lock().unwrap().clone();
        let first = self.id_cmd_first.lock().unwrap().unwrap_or(0);
        let (verbs, _stem) = menu::build(&selection.unwrap_or_default());
        let Some(verb) = menu::verb_from_id(&verbs, idcmd as u32, first) else {
            return Err(E_INVALIDARG.into());
        };
        match utype {
            GCS_VERBA => {
                // ANSI verb name inside the PSTR buffer.
                let name = verb.name();
                let copy = name.len().min(cchmax as usize).saturating_sub(1);
                unsafe {
                    std::ptr::copy_nonoverlapping(name.as_ptr(), pszname.0, copy);
                    *pszname.0.add(copy) = 0;
                }
                Ok(())
            }
            GCS_VERBW => {
                // Wide verb name written through the PSTR buffer as UTF-16.
                let name = verb.name();
                let copy = name.len().min(cchmax as usize).saturating_sub(1);
                let wide_ptr = pszname.0 as *mut u16;
                for (index, &byte) in name.iter().take(copy).enumerate() {
                    unsafe { *wide_ptr.add(index) = byte as u16 };
                }
                unsafe { *wide_ptr.add(copy) = 0 };
                Ok(())
            }
            GCS_VALIDATEW => Ok(()),
            _ => Err(E_INVALIDARG.into()),
        }
    }
}

/// Class factory handed out by `DllGetClassObject`.
#[implement(IClassFactory)]
pub struct AahlClassFactory;

impl AahlClassFactory {
    /// Create a fresh `AahlMenuExt` and hand out the interface matching
    /// `riid`. The returned pointer owns one reference; the caller Releases
    /// it.
    fn create(riid: &GUID) -> Result<*mut c_void> {
        if *riid == IShellExtInit::IID {
            Ok(AahlMenuExt::new().into_interface::<IShellExtInit>().into_raw())
        } else if *riid == IContextMenu::IID {
            Ok(AahlMenuExt::new().into_interface::<IContextMenu>().into_raw())
        } else if *riid == IUnknown::IID {
            Ok(AahlMenuExt::new().into_interface::<IUnknown>().into_raw())
        } else {
            Err(E_NOINTERFACE.into())
        }
    }
}

impl IClassFactory_Impl for AahlClassFactory_Impl {
    fn CreateInstance(
        &self,
        punkouter: Ref<IUnknown>,
        riid: *const GUID,
        ppvobject: *mut *mut c_void,
    ) -> Result<()> {
        if ppvobject.is_null() {
            return Err(E_POINTER.into());
        }
        unsafe { *ppvobject = std::ptr::null_mut() };
        if riid.is_null() {
            return Err(E_POINTER.into());
        }
        if !punkouter.is_null() {
            return Err(CLASS_E_NOAGGREGATION.into());
        }
        let pointer = AahlClassFactory::create(unsafe { &*riid })?;
        unsafe { *ppvobject = pointer };
        Ok(())
    }

    fn LockServer(&self, _flock: BOOL) -> Result<()> {
        Ok(())
    }
}